### ISSUE TITLE
Math.clampBottom removed in r73 of three.js

### ISSUE THREAD

**Issue by kosso** [GQPBJ/Reticulum#12]
Hi,
Great work on this. Thanks!

But a recent release of three.js r73 has removed THREE.Math.clampBottom which is used in reticulum.js 

See : https://github.com/mrdoob/three.js/releases/tag/r73

**Comment by skezo** [comment]
Thanks for highlighting this. 
It should now support  r73.
http://gqpbj.github.io/Reticulum/examples/basic.html
