### ISSUE TITLE
Destroy Reticulum functionality

### ISSUE THREAD

**Issue by mateusvahl** [GQPBJ/Reticulum#22]
I need create a toggle for Reticulum, it's possible to destroy the current plugin from threejs and initiate again some moment latter?

Thanks

**Comment by skezo** [comment]
@mateuspv 

Destroying and initiating it again could be pretty expensive. I would suggest just hiding the reticle and then displaying it again.  This feature is currently not built in but you could do it by setting `proximity: true` and then removing all objects from your hit list `Reticulum.remove( object );`.

I will look at adding this feature so you can hide/disable the reticle and fuse.

**Comment by mateusvahl** [comment]
I made a workaround for my case, since I need Reticulum only on mobile devices,
Thanks for your plugin and attention 👍

**Comment by Akahime** [comment]
+1, I also find this feature useful !
