### ISSUE TITLE
auto brightness on mobile goes dark when inserted into cardboard

### ISSUE THREAD

**Issue by arapps3d** [GQPBJ/Reticulum#23]
Hi! Is there a way to prevent auto brightness on mobile from going dark as soon as I put the device into the cardboard (maybe disable it by code)? Or can this only be adjusted by the user? Thanks.

**Comment by skezo** [comment]
This is controlled by the webvr-polyfill. https://github.com/googlevr/webvr-polyfill/blob/7d5a66ae4ae5f4590d1a5d988a9d0f5038b6145a/src/wakelock.js
