### ISSUE TITLE
Uncaught TypeError: Cannot set property 'x' of undefined with latest three.js

### ISSUE THREAD

**Issue by timmeh4242** [GQPBJ/Reticulum#24]
See description. Lines 108 - 119 in reticulum.js throw the error. I've also altered line 58 to read as follows to get the rings displaying correctly:

```
var geometry = new THREE.RingGeometry( this.innerRadius, this.outerRadius, this.thetaSegments, this.phiSegments, this.thetaStart, Math.PI * 2 );
```

 Possible to take a quick look with the recent changes to the engine and ring geometries? Cheers!

**Comment by skezo** [comment]
Thanks for reporting this. 
This should now be resolved
